language: bash

cache:
    directories:
        - $HOME/.composer/cache

services:
    - docker

install:
    - docker run -v $(pwd):/app -v $HOME/.composer/cache:/tmp composer:1.8 install

script:
    - docker run -v $(pwd):/root/src newtmitch/sonar-scanner ls
    - docker run -v $(pwd):/root/src newtmitch/sonar-scanner cat src/sonar-project.properties
    #    - docker run -v $(pwd):/root/src newtmitch/sonar-scanner sonar-scanner -X -Dproject.settings=./src/sonar-project.properties -Dsonar.login=$SONAR_TOKEN
    - docker run -v $(pwd):/app phpunit/phpunit tests
