language: bash

cache:
    directories:
        - $HOME/.composer/cache

services:
    - docker

install:
    - docker run -v $(pwd):/app -v $HOME/.composer/cache:/tmp composer:1.8 install

before_script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

script:
    - docker run -v $(pwd):/usr/src newtmitch/sonar-scanner -Dsonar.projectBaseDir=/usr/src -Dsonar.login=$SONAR_TOKEN
    - docker run -v $(pwd):/app phpunit/phpunit tests
    - docker-compose exec php-fpm ./vendor/bin/behat

before_deploy:
    - docker build -t $BUILD_NAME -f docker/prod/Dockerfile .

deploy:
    provider: script
    script: echo "Deploy"
    on:
        branch: master