version: '3.6'
services:
    selenium-hub:
        image: selenium/hub:3.141.59-dubnium
    selenium-chrome:
        image: selenium/node-chrome:3.141.59-dubnium
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            HUB_HOST: selenium-hub
            HUB_PORT: 4444
